# Site
repository: usiohc/usiohc.github.io
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 최민수
title: 0년차 백엔드 엔지니어
email: asltn99@gmail.com
website: https://usiohc.tistory.com/
website_title: Tistory
website2: 
website2_title: Portfolio

# Dark Mode (true/false/never)
darkmode: ture

# Social links
# twitter_username: facespics
github_username: usiohc
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: usiohc
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Tistory
#   icon: fa-solid fa-t
#   url: https://usiohc.tistory.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

additional_links:
# - title: Pdf Download
#   icon: far fa-file-pdf
#   url: https://usiohc.github.io/resources/cv.pdf

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: 소개
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  대학 시절에는 다양한 분야를 접해보며 하고싶은 분야를 찾고자 했습니다.
  졸업학년에 ML 수업을 수강하면서 데이터 수집, 전처리에 관심을 가지게 되었고 데이터 엔지니어의 목표를 세우게 되었습니다.

  데이터 엔지니어가 되기 위해 데이터 엔지니어링 데브코스를 수강하면서 데이터 기반 의사결정을 돕기 위한 데이터를 제공하는 파이프라인을 개발하고 데이터 레이크 및 데이터 웨어하우스를 운영하는 역할을 수행하며 대시보드 제작과 분석에 참여 등의 경험을 쌓았습니다. 
  
  개발자의 성장에는 자신이 맡은 바에 최선을 다하는 **책임감**과 **문제해결**을 위한 끈기가 필요하다고 생각합니다. 
  팀의 구성원으로써 신뢰할 수 있는 백엔드 엔지니어가 되고자 하고, 미래에는 DE · DevOps 로 성장하고 싶습니다.
  

  Skills: <mark>Python</mark> <mark>SQL</mark> <mark>Django</mark> <mark>Oracle</mark> <br>
  Data: <mark>Airflow</mark> <mark>Pandas</mark> <mark>Superset</mark> <br>
  Clouds: <mark>AWS</mark> <mark>GCP</mark> <br>
  Tools: <mark>Slack</mark> <mark>Notion</mark> <mark>Docker</mark> <br>


# Projects Section
content:
  - title: <a href="https://usiohc.notion.site/5d8b04ccd7d04823b03217a1a4fa396a?v=274a6e30b60e4c61b6e195f2a681d1e4&pvs=4" target='_blank'>Projects</a> # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 서울 번화가 대시보드
        sub_title: |
          <a href="https://usiohc.notion.site/e7e5987fab83433ca262527574f237e3?pvs=4" target='_blank' style="color: #477dca; font-weight: 500;">포트폴리오 링크</a> <br>
          <a href="https://github.com/data-dev-course/project4-team1" target='_blank' style="color: #477dca; font-weight: 500;">프로젝트 Github 링크</a>
        caption: 2023.08.07 ~ 2023.09.01
        # link: https://usiohc.notion.site/e7e5987fab83433ca262527574f237e3?pvs=4
        # link_text: Notion
        # additional_links:
        #   - title: data-dev-course/project4-team1
        #     icon: fab fa-github
        #     url: github.com/data-dev-course/project4-team1
        quote: >
          서울시에서 번화가로 지정한 113곳의 장소에 대한 인구 현황과 날씨, 주변 맛집과 뉴스를 제공하는 웹
        #  - [Notion을 이용한 Action Item 티켓 관리](https://prgrms.notion.site/3-1-38b1c8aedfcf4f6ba57a908ce90af24d?pvs=4){:target="_blank"}
        # - [프로젝트 Github 링크](https://github.com/data-dev-course/project4-team1){:target="_blank"}
        description: | # this will include new lines to allow paragraphs
          최근 번화가 테러 예고로 인한 사회적인 이슈가 발생함 으로써 번화가의 인구 현황이나 뉴스를 제공하고자 함 <br>
          - [Github 브랜치 전략 수립](https://prgrms.notion.site/Git-Branch-CI-CD-67b8ac8fa8364d2d8140b30506af4ce7?pvs=4){:target="_blank"}
            - 브랜치 전략에 따른 CI/CD를 Github Actions 을 이용해 구현
          - [Elastic Beanstalk](https://prgrms.notion.site/Infra-Elastic-Beanstalk-2de7b4a282494a6fbc64c529916d6450?pvs=4){:target="_blank"} / 
          [Github Actions](https://prgrms.notion.site/Infra-CD-Django-4697db02ae67415995013ce429b70a48?pvs=4){:target="_blank"} 을 이용한 Django 무중단 배포
          - [MWAA, S3](https://prgrms.notion.site/Infra-MWAA-CD-IdP-d8d2c4a41e2748509cbe4a091825d010?pvs=4){:target="_blank"} / 
          [Github Actions](https://prgrms.notion.site/Infra-CD-MWAA-Dags-66c2a690c9ae410d80abc599dce744dc?pvs=4){:target="_blank"} 을 이용한 DAG, requirements 배포
          - [Django 해당 장소별 뉴스 출력](https://prgrms.notion.site/Web-Django-FE-BE-ef5390c80ed645729a0d5cea20db6c48?pvs=4){:target="_blank"}
            - [MWAA를 이용한 네이버 검색 API로 뉴스 데이터를 ETL](https://prgrms.notion.site/Airflow-aa867b3715794bb5902d9c271e80ebb0?pvs=4){:target="_blank"}
            - [crontab을 사용해 S3의 데이터 가져오기](https://prgrms.notion.site/Infra-S3-news-data-to-Elastic-Beanstalk-e70b7314b01843e79ecd63c7bf21b1c5?pvs=4){:target="_blank"}
          <br>
          <br>

          ___
      - layout: left
        title: 유기동물 대시보드
        sub_title: | 
          <a href="https://usiohc.notion.site/c8d9499fb79a4b0eb61bc7116590b215?pvs=4" target='_blank' style="color: #477dca; font-weight: 500;">포트폴리오 링크</a> <br>
          <a href="https://github.com/data-dev-course/project2-team1" target='_blank' style="color: #477dca; font-weight: 500;">프로젝트 Github 링크</a>
        # sub_title: 유기동물 조회 API를 이용한 보호소와 계류상태 분석 및 공고 대시보드
        caption: 1차 2023.05.29 ~ 2023.06.02 <br> 2차 2023.06.26 ~ 2023.06.30
        # link: https://usiohc.notion.site/c8d9499fb79a4b0eb61bc7116590b215?pvs=4
        # link_text: 포트폴리오 링크
        # additional_links:
        #   - title: data-dev-course/project2-team1
        #     icon: fab fa-github
        #     url: github.com/data-dev-course/project2-team1
        quote: >
          다양한 시각의 유기동물 현황 대시보드 및 최신 유기동물 공고 리스트를 제공하는 웹
        description: |
          반려동물을 키우는 인구가 증가하면서 유기되는 동물(개, 고양이)도 계속해서 증가되는 사회문제를 해결해보고자 함 <br>
          
          <small>1차와 2차로 나뉘어 프로젝트를 진행</small><br>
          [1차: 빠르게 MVP 달성을 목표](https://usiohc.tistory.com/50){:target="_blank"}
          - 유기동물 데이터를 1일 ~ 1달 전까지의 데이터를 ETL 하는 python 스크립트 작성 및 Ubuntu 서버에서 crontab
            - 해당 스크립트를 ServerLess 아키텍처로 구현하기 위해 [Cloud Function](https://usiohc.tistory.com/52){:target="_blank"} | 
            [Cloud Scheduler](https://usiohc.tistory.com/55){:target="_blank"} 로 고도화
          - 대시보드 작성을 위한 데이터 웨어하우스(BigQuery)에 Analytics 테이블 작성 (예약된 쿼리 사용)
          - 데이터 탐색과 인사이트 도출을 위해 Superset을 사용, 내부 대시보드의 시각화 차트 작성
          - 프로덕션 웹에서 서비스할 대시보드를 chart.js 라이브러리를 사용해 시각화 차트 작성

          
          [2차: 고도화](https://usiohc.tistory.com/71){:target="_blank"}
          - [Ubuntu에서 Docker Compose를 사용해 Airflow 환경 구축](https://prgrms.notion.site/Airflow-API-to-dag-05fb46d32e9d4b7bb3bc373fdfa0367d?pvs=4){:target="_blank"}
            - Cloud Function을 이용해 데이터 ETL을 수행하던 것을 [Airflow Dag로 작성](https://prgrms.notion.site/Airflow-DAG_Daily_OpenAPI_30days-f27b71b92dd94046b3579426a9c01b87?pvs=4){:target="_blank"}
              - 해당 [DAG를 비동기로 고도화](https://prgrms.notion.site/Airflow-DAG_Daily_OpenAPI_30days-3977073fc8914a02bc2ccb556ecdddbf?pvs=4){:target="_blank"}
            - [당일 데이터를 ETL 하는 DAG 추가](https://prgrms.notion.site/Airflow-DAG_Quarter_OpenAPI_today-30d83d38eb0c4eb2874a882e0bce3e1c?pvs=4){:target="_blank"}
          - [Log 관리 및 GCS로 적재](https://prgrms.notion.site/Airflow-LOG_-b1af5ac4c8c34742a34f3ca0e6fd3a93?pvs=4){:target="_blank"}
            - Ubuntu에 적재되는 [Log, Data를 삭제하는 Dag 추가](https://prgrms.notion.site/Airflow-DAG_Clean_log-data-ce21008004ad4aa9aabded0a3190a529?pvs=4){:target="_blank"}
          <br>
          <br>
          
          ___

      - layout: left
        title: 말달리자
        sub_title:  | 
          <a href="https://usiohc.notion.site/1af0db67573543259742778ef4aa24c6?pvs=4" target='_blank' style="color: #477dca; font-weight: 500;">포트폴리오 링크</a> <br>
          <a href="https://github.com/Inhatc-Bigdata-Project/RacingClassificationModel" target='_blank' style="color: #477dca; font-weight: 500;">프로젝트 Github 링크</a>
        caption: 2022.11 ~ 2022.11
        # link: https://usiohc.notion.site/1af0db67573543259742778ef4aa24c6?pvs=4
        # link_text: Notion
        # additional_links:
        #   - title: Inhatc-Bigdata-Project/RacingClassificationModel
        #     icon: fab fa-github
        #     url: github.com/Inhatc-Bigdata-Project/RacingClassificationModel
        quote: >
          한국마사회에서 제공하는 서울경마 데이터를 크롤링해 3등 이내로 들어온 말을 예측하는 모델을 생성
        description: |
          경마 산업은 국내 합법 사행산업의 큰 비중을 차지, 그러나 사행성 도박이라는 인식으로 인해 타 스포츠 산업에 비해 분석이 미미 함
          - [서울경마](https://race.kra.co.kr/seoulMain.do){:target="_blank"}의 경주성적 / 경주마정보 / 기수정보 데이터를 BeautifulSoup와 Selenium을 이용해 크롤링
          - 데이터 결측치 처리, 정규화, mean encoding 등 전처리 진행
          - 분석과 모델링 팀원이 요청한 데이터 시각화
            - feature Heatmap, feature importance, 범주형 변수 분포, 수치형 변수 분포 등


            
  - title: 수상 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Metaverse & AI 경진대회
        sub_title: 인하공업전문대학 주관<br>금상
        caption: 2022.12
        # additional_links:
        #   - title: RacingClassificationModel
        #     icon: fab fa-github
        #     url: github.com/Inhatc-Bigdata-Project/RacingClassificationModel
        # quote: >
          
        description: | 
          - <b>말달리자</b> 프로젝트로 해당 대회 참가
            - 금상을 수상해 장학금 수여
          - 공모전을 참여하면서 데이터 수집, 전처리 분야를 맡았고 데이터 엔지니어링에 대한 관심을 가지게 되는 계기가 되었음

      - layout: left
        title: 학술논문대회
        sub_title: 한국컴퓨터정보학회 주관<br>우수논문상
        caption: 2022.01
        # additional_links:
        #   - title: Kinect_BMI_Calculator
        #     icon: fab fa-github
        #     url: github.com/Inhatc-StartUp-Project/Kinect_BMI_Calculator
        # quote: >
          
        description: | 
          - [프로젝트 포트폴리오 링크](https://usiohc.notion.site/NET-BMI-d21de3ce487949c3bfec946400fce349?pvs=4){:target="_blank"}
          - 2021년도 코로나로 인해 사람간의 접촉을 지양하는 문화가 발생하면서 비대면으로 신체측정할 수 있는 방법을 고민
          - 공익성과 수익성을 모두 고려하고자 했으며, 저렴한 카메라인 Kinect를 찾을 수 있었고 남성들의 군복무를 위해 진행하는 신체측정을 대상으로 프로젝트를 진행
          - Kinect를 사용해 실시간으로 사람의 신체를 인식하고, 인식된 신체를 통해 BMI를 측정하는 애플리케이션 개발


  - title: 교육 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 데이터 엔지니어링 데브코스 1기
        sub_title: 프로그래머스
        caption: 2023.04 ~ 2023.09
        # quote: >

        description: | 
          - 데이터 엔지니어에게 필요한 역량을 기르고자 참여
          - Airflow, ELT, ETL, Spark, Django, A/B Test, Docker 등을 학습
          - AWS, GCP를 이용해 클라우드 환경에서 데이터 엔지니어링을 경험
          - 처음 만나는 팀원들과의 소통, 협업을 통해 문서화, 기록의 필요성을 깨달음
            - github history, notion, slack, Blog 등을 통해 기록을 남기고자 함

      - layout: left
        title: 인하공업전문대학
        sub_title: 컴퓨터 정보
        caption: 2018.03 ~ 2023.02
        # quote: >
          
        description: | 
          - 관심, 흥미가 생기는 것을 찾기 위해 다양한 분야를 수강
          - [Android, ML, Server, Hadoop, C# .NET, Go, IoT 등을 학습](https://usiohc.notion.site/5d8b04ccd7d04823b03217a1a4fa396a?v=274a6e30b60e4c61b6e195f2a681d1e4&pvs=4){:target="_blank"}
          - 졸업학기에 ML 수업을 수강. 프로젝트를 진행하면서 데이터 수집, 전처리에 관심을 가지게 됨
          - <del>대학 전산실에 2년간 근로를 하면서 하드웨어, 네트워크, 서버 설치와 유지보수 경험</del>

      - layout: left
        title: 학점은행제
        sub_title: 컴퓨터 공학사
        caption: 2023.01 ~ 2023.04
        # quote: >

        description: | 
          - 학사 학위 취득을 위해 CS 기초 수강


  - title: 자격증
    layout: list
    content:
      - layout: top-middle
        title: 정보처리 산업기사
        caption: 2022.09


  - title: Etc
    layout: text
    content: | # this will include new lines to allow paragraphs
      <b>About me</b>
      - Best Practice를 고민하며 개발하는 것을 좋아합니다.
      - 원인을 파악하고 troubleshooting하는것을 좋아합니다.
      - 약속한 기간은 반드시 지키려고 노력합니다.
      
      <br><br>
      <b>개발외의 취미</b>
      - 운동 (풋살, 웨이트)
      - 음악 (약 5년간의 기타 세션)
      - 패션 쇼핑 (무신사 Lv6을 달성)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
